language: python
sudo: false
cache:
  pip: true
python:
- '3.6'
install:
- pip install six
- pip install -U -r requirements.txt
script:
- invoke test
- echo "finished running tests on repo"
- echo " now deploy core lambda pacakges"
- if [ "$TRAVIS_BRANCH" = "production" ]; then echo "Test succeeded! PUBLISHING LAMBDAs";
  echo "we probably should actually do that.." 
  python setup.py test
